### ISSUE TITLE
DESIGN: 홈 화면 UI 개선

### ISSUE THREAD

**Issue by lspc678** [lspc678/Capstone_Frontend#28]
## 👀 이슈 (issue)

- 홈 화면에 있는 UI를 개선하고자 함

## 🚀 to-do

- [ ] 피라미드에 있는 막대기의 크기를 약간 길게 수정

## 🌱 작업한 내용

- [x] 각각의 등록한 기기 밑에 구분선 추가
- [x] 등록된 기기 아이콘 크기를 약간 작게 수정
- [x] 에어컨, 보일러, TV만 사용 여부를 설정할 수 있도록 수정 (냉장고, 세탁기, 전자레인지는 사용 여부를 설정할 수 없도록 수정)

## 📸 스크린샷

![20231121 홈 화면 UI 개선 1](https://github.com/lspc678/Capstone_Frontend/assets/79794123/2729d76c-8a65-4890-9f9f-8fb0cd39d6d4)
